# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Train
        run: python app/classification_train.py

      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > static/misc/report.md
          cat static/misc/metrics.txt > static/misc/report.md

          echo '## Confusion Matrix Plot' >> static/misc/report.md
          echo '![Confusion Matrix](conf_matrix.png)' >> static/misc/report.md

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: static/misc/report.md

      - name: Upload Artifacts
        id: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: |
            static/misc/*
            static/models/*
          compression-level: 0
          overwrite: true


